import sys
import mysql.connector
from mysql.connector import Error

def create_itoi_db(pswd):
    connection = mysql.connector.connect(
        host='localhost',
        database='ITOI_DB',
        user='root',
        password=pswd)

    queryList = [
    """
    CREATE TABLE ORG (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORGNAME VARCHAR(50) NOT NULL UNIQUE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP );
    """,
    """
    CREATE TABLE USER (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    IS_MANAGER BOOLEAN DEFAULT FALSE,
    ORG_ID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_ORG_USER (ORG_ID),
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID));
    """,
    """
    CREATE TABLE MEETING (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MEETING_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    ORG_ID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_ORG_MEETING (ORG_ID),
    FOREIGN KEY (ORG_ID) REFERENCES ORG(ID));
    """,
    """
    CREATE TABLE ATTENDEE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MEETING_ID INT,
    USER_ID INT,
    INDEX IND_MEETING_ATTENDEE (MEETING_ID),
    INDEX IND_USER_ATTENDEE (USER_ID),
    FOREIGN KEY (MEETING_ID) REFERENCES MEETING(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID));
    """,
    """
    CREATE TABLE GOAL (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MEETING_ID INT,
    GOAL_NAME VARCHAR(100) NOT NULL,
    IS_DECIDED BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_MEETING_GOAL (MEETING_ID),
    FOREIGN KEY (MEETING_ID) REFERENCES MEETING(ID));
    """,
    """
    CREATE TABLE DECISION (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GOAL_ID INT, 
    USER_ID INT,
    DECISION_NAME BOOLEAN DEFAULT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_GOAL_DECISION (GOAL_ID),
    INDEX IND_USER_DECISION (USER_ID),
    FOREIGN KEY (GOAL_ID) REFERENCES GOAL(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID));
    """,
    """
    CREATE TABLE SKILL (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MEETING_ID INT,
    SKILL_NAME VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_MEETING_SKILL (MEETING_ID),
    FOREIGN KEY (MEETING_ID) REFERENCES MEETING(ID));
    """,
    """
    CREATE TABLE WEIGHT (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    WEIGHT INT,
    SKILL_ID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_SKILL_WEIGHT (SKILL_ID),
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID));
    """,
    """
    CREATE TABLE RATING (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RATING INT,
    SKILL_ID INT,
    RATING_FOR INT,
    RATING_BY INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IND_SKILL_RATING (SKILL_ID),
    INDEX IND_FOR_RATING (RATING_FOR),
    INDEX IND_BY_RATING (RATING_BY),
    FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID),
    FOREIGN KEY (RATING_FOR) REFERENCES USER(ID),
    FOREIGN KEY (RATING_BY) REFERENCES USER(ID));
    """]

    for query in queryList:
        cursor = connection.cursor()
        cursor.execute(query)
        cursor.close()
        print("Query Executed")

    connection.close()
    print("MySQL connection is closed")


create_itoi_db(str(sys.argv[1]))